<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

	<div class="jumbotron">
		<h1>Sobre</h1>
	</div>
	<div class="col-md-12">
		<h2>A Instituição</h2>
		<p>
			TesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTeste.
		</p>
		<p>
			TesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTeste.
		</p>
		<h2>Nossas Metas</h2>
		<p>
			TesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTeste.
		</p>

		<h2>Valores</h2>
		<p>
			TesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTesteTeste
		</p>
	</div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
